package bookservice.bookorderservice.domain;

public enum OrderStatusEnum {
    NEW, VALIDATED, ALLOCATION_PENDING,VALIDATION_EXCEPTION, ALLOCATED, ALLOCATION_EXCEPTION,

    PENDING_INVENTORY, PICKED_UP, DELIVERED, DELIVERY_EXCEPTION
}